name: bhashantram
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  connectivity_plus: ^3.0.3
  dio: ^5.0.1
  chat_gpt_sdk: 2.1.0
  http: ^0.13.6
  velocity_x: ^3.6.0
  record: ^4.4.4
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  lottie: ^2.3.2
  audio_waveforms: ^1.0.0
  share_plus: ^6.3.0
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/png/

